FROM ghcr.io/iisas/domino-base-piece:latest

# Need to copy pieces source code
COPY config.toml domino/pieces_repository/
COPY pieces domino/pieces_repository/pieces
COPY .domino domino/pieces_repository/.domino

COPY dependencies/requirements-gpu.txt domino/pieces_repository/dependencies/

RUN pip install --no-cache-dir -r domino/pieces_repository/dependencies/requirements-gpu.txt

ENV PYTHONPATH="/home/domino/pieces_repository:${PYTHONPATH}"
